commerce_shipping.commerce_shipping_method.plugin.commerce_postal_delivery:
  type: commerce_shipping_method_configuration
  mapping:
    rate_label:
      type: label
      label: 'Rate label'
    rate_sheet:
      type: integer
      label: 'Rate sheet'
    chars_to_match:
      type: integer
      label: 'Chars to match'
    send_email_to:
      type: string
      label: 'Send email to'
